addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.4.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.3.1")
addSbtPlugin("org.foundweekends" % "sbt-bintray"   % "0.5.6")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"    % "4.0.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.6.1")
